# Generated by Django 6.0.1 on 2026-02-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marco',
            field=models.CharField(blank=True, default='default', max_length=20),
        ),
    ]
