# Generated by Django 6.0.1 on 2026-01-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitioTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('provincia', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ciudad', 'Ciudad turística'), ('cascada', 'Cascada'), ('laguna', 'Laguna'), ('playa', 'Playa'), ('parque', 'Parque nacional'), ('monumento', 'Monumento'), ('cultural', 'Patrimonio cultural'), ('otro', 'Otro')], max_length=20)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sitio turístico',
                'verbose_name_plural': 'Sitios turísticos',
                'ordering': ['nombre'],
            },
        ),
    ]
