# Generated by Django 6.0.1 on 2026-01-31 23:15

import turismo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitioturistico',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitioturistico',
            name='imagen_referencia',
            field=models.ImageField(blank=True, null=True, upload_to=turismo.models.ruta_imagen_sitio, verbose_name='Foto de Referencia para IA'),
        ),
    ]
