# Generated by Django 6.0.1 on 2026-02-01 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_sitioturistico_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitioturistico',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='sitios_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
