# Generated by Django 6.0.1 on 2026-02-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0003_sitioturistico_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitioturistico',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitioturistico',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
